apiVersion: v1
kind: Service
metadata:
  namespace: mysql
  name: mysql
spec:
  ports:
    - name: mysql
      protocol: TCP
      targetPort: 3306
      port: 3306
  selector:
    app: mysql
  clusterIP: None